name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *" # jalan tiap 12 jam
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ranggaardhyy
          outputs: |
            dist/snake-light.svg
            dist/snake-dark.svg?palette=github-dark

      - name: Deploy to output branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: output
          folder: dist
